#!/bin/bash

function check_pods() {
    echo "Checking k8s pods."
    {
        kubectl get pods
    } || {
        echo "kubectl not found"
        exit 0
    }
}

function buildAndInstall() {
    project=$1
    echo "Will start build and install of chainsaw-$project"
    {
    	mvn clean package jib:dockerBuild -f chainsaw-$project
    } || {
        echo "mvn not found or faild"
	exit 0
    }
    {
    kind load docker-image app/chainsaw-$project:0.0.1-SNAPSHOT
    } || {
       echo "kind not present"
    }
    {
        helm upgrade --install $project charts/chainsaw-app-service -f charts/chainsaw-app-service/development/$project-values.yaml
    } || {
        echo "helm not found or faild."
	exit 0
    }
}

function install() {
    check_pods
    {
        echo "Setup minikube docker-env"
        eval $(minikube docker-env)
    } || {
        echo "minikube not found"
        exit 0
    }

    buildAndInstall account-service
    check_pods
}
